class Config:
    ENV_NAME="Pusher-v4"
    STATE_SPACE_SIZE = 23 
    ACTION_SPACE_SIZE = 7
    NUM_EPS = 3
    LEARNING_RATE_PI = 0.001
    LEARNING_RATE_V = 0.001
    PPO_EPOCHS = 4
    BATCH_SIZE = 64
    GAMMA = 0.99
    LAMBDA_GAE = 0.95
    CLIP_PARAM = 0.2
